@if(Auth::user()->isAdmin())
    @include('includes.admin_menu')
@endif
@if(Auth::user()->isStudent())
    @include('includes.student_menu')
    @endif
@if(Auth::user()->isParent())
    @include('includes.student_menu')
@endif
